#!/bin/python

import argparse
from pathlib import Path
import subprocess
import sys

import jinja2
import toml

parser = argparse.ArgumentParser(description='Swap themes.')
parser.add_argument('--config', dest='config_path', default='~/.config/themes/config.toml')
parser.add_argument('theme')

arguments = parser.parse_args()

with Path(arguments.config_path).expanduser().open('r') as file:
    config = toml.load(file)

with (Path(config['general'].get('theme_path') or '~/.config/themes/documents').expanduser()/f'{arguments.theme}.toml').open('r') as file:
    theme = toml.load(file)

theme['style']['opacity_percentage'] = int(theme['style']['opacity']*100)
theme['style']['transparency_percentage'] = 100-theme['style']['opacity_percentage']
a = hex(int(theme['style']['opacity']*255))[2:]
theme['style']['argb_background'] = '#' + a + theme['style']['background'][1:]
theme['style']['rgba_background'] = theme['style']['background'] + a

generate = config['generate']

for source, destination in generate.items():
    with Path(source).expanduser().open('r') as file:
        contents = file.read()
    with Path(destination).expanduser().open('w') as file:
        file.write(jinja2.Template(contents).render(**theme['style']))

script = config['general'].get('script') or theme['general'].get('script')

if script:
    subprocess.run(script, shell=True, stdout=sys.stdout)
